//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrica.Rrhh.Colaboradores.WSEmpleado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MetricaAndina/Colaboradores/IEmpleadoService", ConfigurationName="WSEmpleado.IEmpleadoService")]
    public interface IEmpleadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Obtener", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerFault" +
            "DTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO Obtener(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Obtener", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerRespo" +
            "nse")]
        System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Listar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarFaultD" +
            "TOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> Listar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Listar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Actualizar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarFa" +
            "ultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Actualizar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Actualizar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarRe" +
            "sponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Eliminar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarFaul" +
            "tDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Eliminar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Eliminar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarResp" +
            "onse")]
        System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Insertar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarFaul" +
            "tDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Insertar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Insertar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarResp" +
            "onse")]
        System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServiceChannel : Metrica.Rrhh.Colaboradores.WSEmpleado.IEmpleadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServiceClient : System.ServiceModel.ClientBase<Metrica.Rrhh.Colaboradores.WSEmpleado.IEmpleadoService>, Metrica.Rrhh.Colaboradores.WSEmpleado.IEmpleadoService {
        
        public EmpleadoServiceClient() {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO Obtener(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Obtener(entity);
        }
        
        public System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ObtenerAsync(entity);
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> Listar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Listar(entity);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ListarAsync(entity);
        }
        
        public int Actualizar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Actualizar(entity);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ActualizarAsync(entity);
        }
        
        public int Eliminar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Eliminar(entity);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.EliminarAsync(entity);
        }
        
        public int Insertar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Insertar(entity);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.InsertarAsync(entity);
        }
    }
}
