//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrica.Rrhh.Colaboradores.BL.WSEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
        "ion")]
    [System.SerializableAttribute()]
    public partial class FaultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultDescription {
            get {
                return this.FaultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultDescriptionField, value) != true)) {
                    this.FaultDescriptionField = value;
                    this.RaisePropertyChanged("FaultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultId {
            get {
                return this.FaultIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultIdField, value) != true)) {
                    this.FaultIdField = value;
                    this.RaisePropertyChanged("FaultId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MetricaAndina/Colaboradores/IEmpleadoService", ConfigurationName="WSEmpleado.IEmpleadoService")]
    public interface IEmpleadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Obtener", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSEmpleado.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerFault" +
            "DTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO Obtener(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Obtener", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ObtenerRespo" +
            "nse")]
        System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Listar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSEmpleado.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarFaultD" +
            "TOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> Listar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Listar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ListarRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Actualizar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSEmpleado.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarFa" +
            "ultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Actualizar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Actualizar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/ActualizarRe" +
            "sponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Eliminar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSEmpleado.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarFaul" +
            "tDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Eliminar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Eliminar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/EliminarResp" +
            "onse")]
        System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Insertar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSEmpleado.FaultDTO), Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarFaul" +
            "tDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Insertar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/Insertar", ReplyAction="http://MetricaAndina/Colaboradores/IEmpleadoService/IEmpleadoService/InsertarResp" +
            "onse")]
        System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServiceChannel : Metrica.Rrhh.Colaboradores.BL.WSEmpleado.IEmpleadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServiceClient : System.ServiceModel.ClientBase<Metrica.Rrhh.Colaboradores.BL.WSEmpleado.IEmpleadoService>, Metrica.Rrhh.Colaboradores.BL.WSEmpleado.IEmpleadoService {
        
        public EmpleadoServiceClient() {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO Obtener(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Obtener(entity);
        }
        
        public System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ObtenerAsync(entity);
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO> Listar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Listar(entity);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ListarAsync(entity);
        }
        
        public int Actualizar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Actualizar(entity);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.ActualizarAsync(entity);
        }
        
        public int Eliminar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Eliminar(entity);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.EliminarAsync(entity);
        }
        
        public int Insertar(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.Insertar(entity);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Entity.DTO.EmpleadoDTO entity) {
            return base.Channel.InsertarAsync(entity);
        }
    }
}
