//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrica.Rrhh.Colaboradores.Test.WSRequerimiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Entity.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.ClienteDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.CandidatoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.PostulanteDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO))]
    public partial class BaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((this.AccionField.Equals(value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModificacion {
            get {
                return this.UsuarioModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificacionField, value) != true)) {
                    this.UsuarioModificacionField = value;
                    this.RaisePropertyChanged("UsuarioModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Entity.DTO")]
    [System.SerializableAttribute()]
    public partial class ClienteDTO : Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoContactoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailContacto {
            get {
                return this.EmailContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailContactoField, value) != true)) {
                    this.EmailContactoField = value;
                    this.RaisePropertyChanged("EmailContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoContacto {
            get {
                return this.TelefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoContactoField, value) != true)) {
                    this.TelefonoContactoField = value;
                    this.RaisePropertyChanged("TelefonoContacto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidatoDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Entity.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.PostulanteDTO))]
    public partial class CandidatoDTO : Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisponibilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradoEstudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroHijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PretencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoPersonalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cv {
            get {
                return this.CvField;
            }
            set {
                if ((object.ReferenceEquals(this.CvField, value) != true)) {
                    this.CvField = value;
                    this.RaisePropertyChanged("Cv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Disponibilidad {
            get {
                return this.DisponibilidadField;
            }
            set {
                if ((this.DisponibilidadField.Equals(value) != true)) {
                    this.DisponibilidadField = value;
                    this.RaisePropertyChanged("Disponibilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradoEstudio {
            get {
                return this.GradoEstudioField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoEstudioField, value) != true)) {
                    this.GradoEstudioField = value;
                    this.RaisePropertyChanged("GradoEstudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPuesto {
            get {
                return this.IdPuestoField;
            }
            set {
                if ((this.IdPuestoField.Equals(value) != true)) {
                    this.IdPuestoField = value;
                    this.RaisePropertyChanged("IdPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroHijos {
            get {
                return this.NumeroHijosField;
            }
            set {
                if ((this.NumeroHijosField.Equals(value) != true)) {
                    this.NumeroHijosField = value;
                    this.RaisePropertyChanged("NumeroHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pretencion {
            get {
                return this.PretencionField;
            }
            set {
                if ((this.PretencionField.Equals(value) != true)) {
                    this.PretencionField = value;
                    this.RaisePropertyChanged("Pretencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCasaField, value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoPersonal {
            get {
                return this.TelefonoPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoPersonalField, value) != true)) {
                    this.TelefonoPersonalField = value;
                    this.RaisePropertyChanged("TelefonoPersonal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostulanteDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Entity.DTO")]
    [System.SerializableAttribute()]
    public partial class PostulanteDTO : Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.CandidatoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIniContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPostulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRequerimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinContrato {
            get {
                return this.FechaFinContratoField;
            }
            set {
                if ((this.FechaFinContratoField.Equals(value) != true)) {
                    this.FechaFinContratoField = value;
                    this.RaisePropertyChanged("FechaFinContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIniContrato {
            get {
                return this.FechaIniContratoField;
            }
            set {
                if ((this.FechaIniContratoField.Equals(value) != true)) {
                    this.FechaIniContratoField = value;
                    this.RaisePropertyChanged("FechaIniContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPostulacion {
            get {
                return this.FechaPostulacionField;
            }
            set {
                if ((this.FechaPostulacionField.Equals(value) != true)) {
                    this.FechaPostulacionField = value;
                    this.RaisePropertyChanged("FechaPostulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRequerimiento {
            get {
                return this.IdRequerimientoField;
            }
            set {
                if ((this.IdRequerimientoField.Equals(value) != true)) {
                    this.IdRequerimientoField = value;
                    this.RaisePropertyChanged("IdRequerimiento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequerimientoDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Entity.DTO")]
    [System.SerializableAttribute()]
    public partial class RequerimientoDTO : Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.ClienteDTO ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTentativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdenCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.PostulanteDTO> PostulacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoSalarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.ClienteDTO Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTentativa {
            get {
                return this.FechaTentativaField;
            }
            set {
                if ((this.FechaTentativaField.Equals(value) != true)) {
                    this.FechaTentativaField = value;
                    this.RaisePropertyChanged("FechaTentativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdenCompra {
            get {
                return this.OrdenCompraField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenCompraField, value) != true)) {
                    this.OrdenCompraField = value;
                    this.RaisePropertyChanged("OrdenCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.PostulanteDTO> Postulaciones {
            get {
                return this.PostulacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.PostulacionesField, value) != true)) {
                    this.PostulacionesField = value;
                    this.RaisePropertyChanged("Postulaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RangoSalario {
            get {
                return this.RangoSalarioField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoSalarioField, value) != true)) {
                    this.RangoSalarioField = value;
                    this.RaisePropertyChanged("RangoSalario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
        "ion")]
    [System.SerializableAttribute()]
    public partial class FaultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultDescription {
            get {
                return this.FaultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultDescriptionField, value) != true)) {
                    this.FaultDescriptionField = value;
                    this.RaisePropertyChanged("FaultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultId {
            get {
                return this.FaultIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultIdField, value) != true)) {
                    this.FaultIdField = value;
                    this.RaisePropertyChanged("FaultId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MetricaAndina/Colaboradores/IRequerimientoService", ConfigurationName="WSRequerimiento.IRequerimientoService")]
    public interface IRequerimientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ob" +
            "tener", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ob" +
            "tenerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.FaultDTO), Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ob" +
            "tenerFaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO Obtener(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ob" +
            "tener", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ob" +
            "tenerResponse")]
        System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Li" +
            "star", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Li" +
            "starResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.FaultDTO), Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Li" +
            "starFaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO> Listar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Li" +
            "star", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Li" +
            "starResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/In" +
            "sertar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/In" +
            "sertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.FaultDTO), Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/In" +
            "sertarFaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Insertar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/In" +
            "sertar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/In" +
            "sertarResponse")]
        System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ac" +
            "tualizar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ac" +
            "tualizarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.FaultDTO), Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ac" +
            "tualizarFaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Actualizar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ac" +
            "tualizar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/Ac" +
            "tualizarResponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/El" +
            "iminar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/El" +
            "iminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.FaultDTO), Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/El" +
            "iminarFaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        int Eliminar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/El" +
            "iminar", ReplyAction="http://MetricaAndina/Colaboradores/IRequerimientoService/IRequerimientoService/El" +
            "iminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequerimientoServiceChannel : Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.IRequerimientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequerimientoServiceClient : System.ServiceModel.ClientBase<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.IRequerimientoService>, Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.IRequerimientoService {
        
        public RequerimientoServiceClient() {
        }
        
        public RequerimientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequerimientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequerimientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequerimientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO Obtener(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.Obtener(entity);
        }
        
        public System.Threading.Tasks.Task<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO> ObtenerAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.ObtenerAsync(entity);
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO> Listar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.Listar(entity);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO>> ListarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.ListarAsync(entity);
        }
        
        public int Insertar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.Insertar(entity);
        }
        
        public System.Threading.Tasks.Task<int> InsertarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.InsertarAsync(entity);
        }
        
        public int Actualizar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.Actualizar(entity);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.ActualizarAsync(entity);
        }
        
        public int Eliminar(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.Eliminar(entity);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(Metrica.Rrhh.Colaboradores.Test.WSRequerimiento.RequerimientoDTO entity) {
            return base.Channel.EliminarAsync(entity);
        }
    }
}
