//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrica.Rrhh.Colaboradores.WSUtil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MetricaAndina/Colaboradores/IUtilService", ConfigurationName="WSUtil.IUtilService")]
    public interface IUtilService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarEstadoXDominio" +
            "", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarEstadoXDominio" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarEstadoXDominio" +
            "FaultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarEstadoXDominio(int dominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarEstadoXDominio" +
            "", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarEstadoXDominio" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarEstadoXDominioAsync(int dominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarSkillTecnico", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarSkillTecnicoRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarSkillTecnicoFa" +
            "ultDTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarSkillTecnico(int idPuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarSkillTecnico", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarSkillTecnicoRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarSkillTecnicoAsync(int idPuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarDistritos", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarDistritosRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Metrica.Rrhh.Colaboradores.BL.WSNotificacion.FaultDTO), Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarDistritosFault" +
            "DTOFault", Name="FaultDTO", Namespace="http://schemas.datacontract.org/2004/07/Metrica.Rrhh.Colaboradores.Service.Extens" +
            "ion")]
        System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarDistritos(string ubigeo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarDistritos", ReplyAction="http://MetricaAndina/Colaboradores/IUtilService/IUtilService/ListarDistritosRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarDistritosAsync(string ubigeo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilServiceChannel : Metrica.Rrhh.Colaboradores.WSUtil.IUtilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilServiceClient : System.ServiceModel.ClientBase<Metrica.Rrhh.Colaboradores.WSUtil.IUtilService>, Metrica.Rrhh.Colaboradores.WSUtil.IUtilService {
        
        public UtilServiceClient() {
        }
        
        public UtilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarEstadoXDominio(int dominio) {
            return base.Channel.ListarEstadoXDominio(dominio);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarEstadoXDominioAsync(int dominio) {
            return base.Channel.ListarEstadoXDominioAsync(dominio);
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarSkillTecnico(int idPuesto) {
            return base.Channel.ListarSkillTecnico(idPuesto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarSkillTecnicoAsync(int idPuesto) {
            return base.Channel.ListarSkillTecnicoAsync(idPuesto);
        }
        
        public System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO> ListarDistritos(string ubigeo) {
            return base.Channel.ListarDistritos(ubigeo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Metrica.Rrhh.Colaboradores.Entity.DTO.ItemDTO>> ListarDistritosAsync(string ubigeo) {
            return base.Channel.ListarDistritosAsync(ubigeo);
        }
    }
}
